# The comments are too noisy to be useful
comment: false

# Enable annotations on PRs to get detailed feedback on coverage
# https://docs.codecov.io/docs/github-checks-beta
github_checks:
  annotations: true  # Annotations enabled to review fluctuation issues

coverage:
  range: "36...100"
  status:
    project:
      default:
        # Dropping slightly is ok - this stops the check failing on test timing variability
        # 0.12 was observed as the largest variability owing to timing forcing different test branch choice
        threshold: 0.15
        # BUG: our coverage fluctuates, so Codecov marks this as a build failure (#12227)
        # Stop Codecov from failing CI until this is fixed
        # https://docs.codecov.com/docs/commit-status#informational
        informational: true
    patch:
      default:
        # BUG: our coverage fluctuates, so Codecov marks this as a build failure (#12227)
        # Stop Codecov from failing CI until this is fixed
        # https://docs.codecov.com/docs/commit-status#informational
        informational: true