name: 🐞 Bug
description: File a bug
title: "[BUG]: "
labels:  [Bug]

body:

  - type: checkboxes
    id: contact
    attributes:
      label: Is there an existing issue for this?
      description: Please go through [open issues](https://github.com/ankidroid/Anki-Android/issues), to see if anything similar already exists.
      options:
        - label: This issue is not a duplicate
          required: true

  - type: textarea
    id: steps
    attributes:
      label: What are the steps to reproduce this bug?
      placeholder: briefly explain the steps.
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: A concise discription of what you expect to happen.
      placeholder: Expected behaviour.
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Current behaviour?
      description: A concise discription of what you are experiencing.
      placeholder: Actual behaviour.
    validations:
      required: true

  - type: textarea
    id: debug-info
    attributes:
      label: Debug info
      description: Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
      placeholder: Debug info.
    validations:
      required: true

  - type: textarea
    id: extra_info
    attributes:
      label: Is there anything else you want to share?
      placeholder: discibe any extra information.

  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Confirm the points below
      options:
        - label: I am reporting a bug/enhancement request specific to AnkiDroid.
          required: true
        - label: I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue.
          required: true
        - label: I have confirmed the issue is not resolved in the latest alpha release [instructions](https://docs.ankidroid.org/manual.html#betaTesting).
