name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels:  [Bug] 

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug/issue report!
  - type: checkboxes
    id: contact
    attributes:
      label: Is there an existing issue for this?
      description: Please go through open issues, to see if anything similar already exists.
      options:
      - label: I have searched the existing issues
        required: true
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: What are the steps to reproduce this bug?
      description: tell briefly what are the steps to reproduce this bug.
      placeholder: Tell us what you see!
      value: "1. "
    validations:
      required: true     
  - type: textarea
    id: what-happened
    attributes:
      label: Reproduction steps
      description: write clear steps to reproduce this bug.
      placeholder: Tell us what you see!
      value: >
      "1"
      "2"
    validations:
      required: true   
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
