/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ichi2.anki;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int wb_bg_color=0x7f050001;
        public static final int wb_fg_color=0x7f050000;
    }
    public static final class drawable {
        public static final int anki=0x7f020000;
    }
    public static final class id {
        public static final int card_action=0x7f060007;
        public static final int card_time=0x7f060004;
        public static final int files=0x7f060009;
        public static final int flashcard=0x7f060000;
        public static final int my_id=0x7f060006;
        public static final int sel_result=0x7f060003;
        public static final int show_answer=0x7f060002;
        public static final int statusbar=0x7f060008;
        public static final int toggle_overlay=0x7f060005;
        public static final int whiteboard=0x7f060001;
    }
    public static final class layout {
        public static final int flashcard_portrait=0x7f030000;
        public static final int flashcard_wide=0x7f030001;
        public static final int main=0x7f030002;
        public static final int main_fileentry=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int card_hint=0x7f040004;
        public static final int card_template=0x7f040005;
        public static final int overlay_off=0x7f040002;
        public static final int overlay_on=0x7f040001;
        public static final int show_answer=0x7f040003;
    }
}
